name: SopDisplays
version: ${project.version}
main: net.enelson.sopdisplays.SopDisplays
api-version: '1.16'
authors: [E_NeLsOn]
depend: [ProtocolLib, SopLib]
softdepend: [PlaceholderAPI]
commands:
  sopdisplays:
    aliases: [sd,displays]
    description: Manage displays
    usage: /sopdisplays <create|remove|movehere|item|text|list|reload>
